steps:
  - label: ":lint-roller: Lint dockerfile"
    command: "find . -iname '*dockerfile' -exec hadolint '{}' +"
    plugins:
      - docker#v3.8.0:
          image: hadolint/hadolint:latest-alpine

  - label: ':lint-roller: Lint scripts'
    command:
      - shellcheck ./*.sh
    plugins:
      - docker#v3.8.0:
          image: koalaman/shellcheck-alpine:v0.7.0

  - label: ':lint-roller: Lint Elixir'
    command:
      - mix format --check-formatted
    plugins:
      - docker#v3.8.0:
          image: elixir:1.13

  - label: ":hammer: Build & Test(1.12)"
    command:
     - docker build --pull --progress=plain \
       --arg=elixir_version=1.12
       --file Dockerfile .

  - label: ":hammer: Build & Test(1.13)"
    command:
     - docker build --pull --progress=plain \
       --arg=elixir_version=1.13
       --file Dockerfile .
